### ISSUE TITLE
Volume Wheel Not Controlling Volume

### ISSUE THREAD

**Issue by wolffman007** [kiteretro/Circuit-Sword#109]
Everything seems to be working fine within the image with the exception of the volume wheel controlling the volume.  As of now, volume wheel has no effect at all.

Volume can still be turned up/down within the Retropie menu.  Looks like it is set to "PCM" as the audio device with the OMX player set to "Both".  Headphones do not auto-switch but if I turn them on in the retropie menu it works.

Any fixes for getting the volume wheel to control?

**Comment by kiteretro** [comment]
Have you followed the steps to enable the volume wheel? https://github.com/kiteretro/Circuit-Sword/wiki/Circuit-Sword-FAQ#how-do-i-enable-the-volume-wheel

**Comment by wolffman007** [comment]
I did not!  Ran the script and its working perfectly - somehow missed that in the wiki.  Thanks for the reply and what an amazing board you created... really great stuff.
