### ISSUE TITLE
[Next] Add Volume OSD overlay

### ISSUE THREAD

**Issue by c-hri-s** [kiteretro/Circuit-Sword#21]
It would be useful to have a visual representation of the current volume on-screen when you're changing it, so you can understand how loud you're adjusting it. Without a physical volume switch it's difficult to gauge.

This would be particularly useful when modifying it from ES when you may be adjusting it with no sound actually playing.

Something like a simpler version of the iPhone volume graphic https://i.stack.imgur.com/OJmvI.gif

**Comment by kiteretro** [comment]
Agree 100% and I have ideas on doing so :) It will also do the same for brightness, and any other 'state change' (e.g. turning wifi on/off).

It will also incorporate a menu that will be able to adjust certain settings (e.g. 'calibrate joystick now', 'calibrate battery voltage', 'invert joystick axis', etc)

Thanks for raising this, I will be using it to track progress.

**Comment by c-hri-s** [comment]
Sounds great!

**Comment by StanMOI** [comment]
waiting for update

**Comment by StanMOI** [comment]
Did anyone already done this option by him self?

**Comment by kiteretro** [comment]
I have some work in progress, nothing committed yet, but don't worry i'm still working on this :)

**Comment by StanMOI** [comment]
YES!
You are the BEST !

**Comment by cvondra** [comment]
Any ETA on when we may see this functionality?

**Comment by kiteretro** [comment]
Within the next 2 months. The software that contains this is also required by the Circuit Sword Lite, so when those are here (they were in the latest order a month ago) I literally HAVE to have it ready, and I'll do it for the CSO too :) there are some other notable improvements so it'll be worth the wait!

**Comment by kiteretro** [comment]
Fixed in https://github.com/kiteretro/Circuit-Sword/releases/tag/v1.3.0

**Comment by c-hri-s** [comment]
Certainly is - nice OSD, thanks Kite! :)
