### ISSUE TITLE
[Issue] No sound from speaker

### ISSUE THREAD

**Issue by jamesalmeida** [kiteretro/Circuit-Sword#24]
Sound works through the headphone jack but not through the speaker. I soldered the red wire to the positive (+) and black wire to the negative (-) on the speaker and then plugged it into the speaker port on the board. Is that how it's supposed to be installed? Would it be an issue if the back of the speaker is pressed up against the battery bay or would that not matter? I'm going to take it apart when I get home and see if it works when I remove the back of the casing to be sure.

**Comment by kiteretro** [comment]
That all sounds good James, could you see if in the top right corner there is a speaker icon shown? If yes then that's the MUTE icon (which disables the amp) .. could you do like MODE + X (i think) to disable it, otherwise it's MODE + Y ?

Send a pic of how it's connected, make sure the connector is all the way in :)

**Comment by kiteretro** [comment]
Did you get this fixed James?

**Comment by jamesalmeida** [comment]
Haven't been able to check connector and take a pic of inside yet.

**Comment by jamesalmeida** [comment]
The connector is all the way in and the sound is turned on. Still nothing comes out of speaker. Only sound that works is through the headphone jack.  

Here's a pic of my speaker:
![img_0896 1](https://user-images.githubusercontent.com/703253/36948828-8add0fa8-1fae-11e8-9bbd-88530c9de392.jpg)

**Comment by kiteretro** [comment]
Have you got another speaker to try? Like on those solder pads next to it? 

Could you measure the voltage on this resistor to gnd: 

![image](https://user-images.githubusercontent.com/7543492/36950547-619b0230-1fef-11e8-9934-7bc292b106c7.png)

**Comment by kiteretro** [comment]
Closing issue, re-open or send me an email if needed.

**Comment by jamesalmeida** [comment]
I measured it and it says 3.27

**Comment by jamesalmeida** [comment]
@kiteretro I measured it and it says 3.27

Still no sound from speaker. Tried another speaker too. I do get sound through headphone jack though.

**Comment by kiteretro** [comment]
From that picture above, it looks as if the speaker trace has been damaged (see just above where the "S-" hole connector is. Could you try and clean up that area and get a clear photo of it. It might help to have some strong light and view it from an angle..

What you might need to do is gently scrape the black off the trace and bridge it with some solder.

This is what that area looks like from the design:

![image](https://user-images.githubusercontent.com/7543492/50822315-5dcfd800-1329-11e9-97b9-233b52a2795b.png)

**Comment by jamesalmeida** [comment]
@kiteretro That stuff above the S- hole is glue from my hot glue gun that was holding the speaker in place. Do you think hot glue could have damaged the trace?

**Comment by jamesalmeida** [comment]
@kiteretro Sound just started working! Thanks for your help!
