### ISSUE TITLE
[Issue] Can't seem to get wifi to turn on

### ISSUE THREAD

**Issue by ToeMachine** [kiteretro/Circuit-Sword#25]
As mentioned, can't seem to get wifi to turn on, I've tried the mode + A button combo, not sure what else to do.

**Comment by kiteretro** [comment]
Hi can you provide more information, for example how have you determined that it is not on?

Could you please follow these steps and upload the log file here please https://github.com/kiteretro/Circuit-Sword/wiki/Troubleshooting-(LCD-Power-USB-Software)#collecting-the-log-file

**Comment by ToeMachine** [comment]
Apologies for the quick issue post, will check for physical shorts on wifi module as mentioned in the link included. Cheers!
