### ISSUE TITLE
[Issue] I can not booted up the system

### ISSUE THREAD

**Issue by FoRTu** [kiteretro/Circuit-Sword#27]
Hello,

I don't know if I'm doing something wrong but I can not booted up the system. I try diferent types of SD cards getting the same result, the screen flash after I switch on but nothing apears on the screen. As I can read on FAQs I wait some minutes to resize the file system but aften 10 minutes the board looks the same.

I try to [disable the wifi](https://github.com/kiteretro/Circuit-Sword/wiki/Troubleshooting-(LCD-Power-USB-Software)#disabling-wifi-completely) editing the config.txt but still the same.

Here is a image of how looks the board when is booted up:

![Can not boot it up](https://user-images.githubusercontent.com/633679/36743510-c0f9eaec-1bea-11e8-87d0-5e8907f5c5a8.jpg)

You can see on the image the two types of SD card I use (with the same result).

Thank you

**Comment by kiteretro** [comment]
Hm, the 1V8 LED isn't on, if you remove the CM3 and power the board does the 1v8 LED come on at all? If it doesn't, can you send me an email as it'll need to be returned as it is faulty and I will send you out a new one right away! So please send me an email to kite@kitesitemshop.com :)

**Comment by FoRTu** [comment]
Thank you for your quick response.

Yes, the 1V8 LED isn't on as you can see in the image below, with and without CM3. 

![led_1v8](https://user-images.githubusercontent.com/633679/36800693-6cf54e8e-1cb0-11e8-9167-61c9faaf661a.jpg)

And Here is the picture of the underneath of the CM3:

![undereath_cm3](https://user-images.githubusercontent.com/633679/36800716-7b806218-1cb0-11e8-9af3-d54a082a17ae.jpg)

Before send you a mail to proceed to return the board, is there any solution to solve it? soldering something?

Thank you.

**Comment by kiteretro** [comment]
The only thing that looks amis is the inductor here:

![image](https://user-images.githubusercontent.com/7543492/36802728-9cc1104c-1cad-11e8-85de-266bc857be0b.png)

Do you have hot air reflow equipment? Or do you have solder and flux? If possible, try adding hot solder to either side of that inductor, one at a time..

**Comment by FoRTu** [comment]
I don't have any hot air reflow equipment, and I think that haven't enough experience soldering to do that. So, I think the best way is to return the board and replace for another one.

I send you a mail to kite@kitesitemshop.com to proceed.

Thanks for the support.

**Comment by kiteretro** [comment]
Closing as board has been repaired and will be sent back shortly
