### ISSUE TITLE
[Next] One time reboot to HDMI with full resolution

### ISSUE THREAD

**Issue by kiteretro** [kiteretro/Circuit-Sword#28]
Some kind of menu option for "One time reboot to HDMI" which will allow for HDMI to be FULL HD resolution, and then cloned back to the internal screen.. this will allow you to actually use it on a TV with something nicer than 320x240!

**Comment by jfenton78** [comment]
A recent post on reddit discuses auto-switching between an LCD and HDMI-Out. This may be a solution for the one time reboot to HDMI.

https://www.reddit.com/r/raspberry_pi/comments/6lq09q/autoswitch_between_lcd_and_hdmiout/

**Comment by kiteretro** [comment]
Indeed, the complication is linking it up to the `dpi-cloner` binary because different parameters would be needed to clone from HDMI to the internal screen. It's all very possible :) low on my list because HDMI and LCD cloning already works, but def can do with improving as you have suggested. Thank you for the link!

**Comment by kiteretro** [comment]
+ add audio over HDMI

**Comment by kiteretro** [comment]
Fixed in https://github.com/kiteretro/Circuit-Sword/releases/tag/v1.3.0
