### ISSUE TITLE
Digital Volume control switch controls backwards 

### ISSUE THREAD

**Issue by markolomew** [kiteretro/Circuit-Sword#30]
I'm finally testing the Digital Volume Controller Switch with a speaker, and the Switch Up is Volume Down and the Switch Down is Volume up.

I'm connected just as the github shows,  so should I swap the wires for A-RX and A-TX or is this a software thing that I should wait for a fix/update?

**Comment by markolomew** [comment]
Just a reminder to update the github documents to reflect this change.  Issues is resolved though, so I am closing issue.

**Comment by kiteretro** [comment]
Thanks @markolomew for the reminder. I have updated the picture on this page: https://github.com/kiteretro/Circuit-Sword/wiki/Digital-Volume-Guide
