### ISSUE TITLE
[Issue] Select and Start not Mapping correctly 

### ISSUE THREAD

**Issue by thebadbishop** [kiteretro/Circuit-Sword#36]
Hi, my unit is saying the select button is already taken when I attempt to map it.
I skipped the mapping of select, and it turns out the select and start buttons are both regestering as a “Start” push.

Please let me know how to fix this issue.

**Comment by kiteretro** [comment]
Hi, can you please take a close up, in focus, in light, picture of this area (it is just above where the DPAD is):

![image](https://user-images.githubusercontent.com/7543492/37704510-f1a4b368-2cf0-11e8-9564-9ac14a4cd145.png)

Could you also take a picture in the same way of the start and select buttons:

![image](https://user-images.githubusercontent.com/7543492/37704573-152c36ee-2cf1-11e8-8bfd-f69a9749937e.png)

Are you also able to connect it to a PC and use the "USB GAMEPAD" option in windows to see what button does what? https://github.com/kiteretro/Circuit-Sword/wiki/Configuration-Switches

**Comment by thebadbishop** [comment]
No PC access at this moment, but here are some photos:
![60bc45d8-4ae3-451a-840f-ad6958e7d539](https://user-images.githubusercontent.com/37567629/37732730-2331992a-2d03-11e8-8b64-abe943f8dd4f.jpeg)
![bb267e55-16c9-44d3-80af-c91085c74b75](https://user-images.githubusercontent.com/37567629/37732731-2357823e-2d03-11e8-97e9-86ea6f4318de.jpeg)
![bc8bb4c1-922a-4291-b406-0b30fe5fcadd](https://user-images.githubusercontent.com/37567629/37732732-2374210a-2d03-11e8-8299-b5eaf83ab646.jpeg)
![d1bb244f-0411-44c7-8e78-f896ac068bd5](https://user-images.githubusercontent.com/37567629/37732733-238ec0e6-2d03-11e8-8de6-1bdd47863b89.jpeg)
![Uploading 7D2C616F-902D-4981-A762-4A4F4B6988A0.jpeg…]()

**Comment by thebadbishop** [comment]
Got a little closer on what I think is the issue (after looking at the 2 places you pointed out)
![d9a13ed1-959c-4c38-97cd-04772d5e7f2a](https://user-images.githubusercontent.com/37567629/37733288-d4642612-2d04-11e8-8af7-006d35225f78.jpeg)

**Comment by kiteretro** [comment]
There's your issue :) how are you with a soldering iron and sucker/braid? Do you know anyone who may be able to help?

What you need to do is apply flux to the area (this is a MUST) and then heat up the solder bridge, then using a solder sucker on it to pull away the excess!

I can repair this for free if you send me an email, but it would be easier if someone local could help you. It's worth trying that first, and as long as you literally don't put HOLES on the board then whatever the result is I can repair anyway..

**Comment by thebadbishop** [comment]
That worked!

... but now my unit is flickering... the screen flickers off an on and it seems to be running hot not sure if related (and i have both the fan and heatsink working).

**Comment by kiteretro** [comment]
Ok is this still happening? If you remove the CM3 and under where it is, should be an LED "BL", is this glowing brightly? ALso is the chip next to it really hot? (be careful it may burn you if so)? Or are you meaning some other chip is hot?

**Comment by thebadbishop** [comment]
The flickering seems to only be an issue when the battery is low.

As for the heating, it doesn’t seem to be as bad now (I removed my cosmetic cartridge to allow for more airflow)

**Comment by kiteretro** [comment]
Ok, I'm going to close this issue as fixed. If there are problems with any component getting too hot, or anything stops working, please let me know (e.g. raise a new issue or email me). In normal use nothing should get too hot for you to hold your finger on.
