### ISSUE TITLE
Digital volume isn't very responsive

### ISSUE THREAD

**Issue by kiteretro** [kiteretro/Circuit-Sword#4]
The digital volume adjust (MODE + UP/DOWN) works but is very slow to respond. Need to re-do the logic for requesting serial data!

**Comment by kiteretro** [comment]
Closing this issue for now. A better handling of all this serial data is coming soon!

**Comment by timetraveler0110** [comment]
Kite, 5his is Juanje from Sudomod
I’m having trouble with digital volume combo mode
I put an issue, with your permission
Thx Mr Kite
