### ISSUE TITLE
[Issue] Dreamcast emulator doesn't work with buttons or d-pad

### ISSUE THREAD

**Issue by jamesalmeida** [kiteretro/Circuit-Sword#44]
I got the Dreamcast emulator running but can't seem to program the buttons or d-pad to actually control anything. I can only boot up the app for setting the system time but can't actually set the time. If I can't set the time I can't load any other roms. Has anyone else been able to get the Dreamcast emulator working with the built-in Circuit Sword buttons?

**Comment by jamesalmeida** [comment]
Anyone know how I can get around this issue?

**Comment by kiteretro** [comment]
What have you got in your mapping file?

**Comment by kiteretro** [comment]
Did a quick test, worked fine, perhaps after installing you need to do the 'configure gamepad' steps again from the ES menu?
