### ISSUE TITLE
[Documentation] FPC Pinout?

### ISSUE THREAD

**Issue by tonious** [kiteretro/Circuit-Sword#45]
Hi Kite!

Would you consider publishing the pinout for the FPC connector?  I've been considering designing my own backboard.

(I love the product, btw)

**Comment by kiteretro** [comment]
Of course! For the time being, here is the information:

**Connector:** FPC 26P 'clam shell' connector

**Pinout:**
![image](https://user-images.githubusercontent.com/7543492/39630953-cb1672ec-4fa8-11e8-867d-ce0c742559c2.png)

**Pin orientation (top view):**
![image](https://user-images.githubusercontent.com/7543492/39631537-5a949da8-4faa-11e8-8853-5b32d35d6193.png)

Pinout should be self explanatory! If not, let me know. It is recommended to use 22R resistors in series with the USB data lines (so one on DP and one on DM).

**Comment by gustavodlt1** [comment]
@kiteretro hello, good morning, I don't speak English so I used the google translator, I want to do an sd adapter for ps2, I wanted to know if you could be so kind as to make me a pinout of an 8 pin fpc connector to add a usb output. this is the product to which I want to add the usb output https://es.aliexpress.com/item/32858177828.html?spm=a2g0o.productlist.0.0.2a5619e3ih7IHl&algo_pvid=d9734390-52db-4bc0-bf67-6b2a0994d21a&algo_exp_id=d9734390-52db-4bc0-bf67-6b2a0994d21a-0&pdp_ext_f=%7B%22sku_id%22%3A%2265342270081%22%7D&pdp_npi=1%40dis%7CARS%7C%7C248.23%7C%7C%7C%7C%7C%402101e9d116511676894652481ea929%7C65342270081%7Csea
