### ISSUE TITLE
New power switch is too close to case for OEM switch

### ISSUE THREAD

**Issue by JamesHagerman** [kiteretro/Circuit-Sword#49]
I'm posting here because I can't figure out where to post on sudomod.

I finally went to assemble my Circuit Sword and ran into a problem with how the power switch should be installed.

I'm using HoolyHoo's glue-less bracket: [https://sudomod.com/forum/viewtopic.php?f=58&t=5321](https://sudomod.com/forum/viewtopic.php?f=58&t=5321)

When I install everything, there's almost zero space between the switch lever and the back of the case:

![zoom-1](https://user-images.githubusercontent.com/1037176/41396907-41dceab8-6f67-11e8-8086-b464350e7e4b.PNG)

However, the switch expects a good amount of space between the switch lever and the back of the case so that the lever can enter close to the center of the switch body:

![zoom-2](https://user-images.githubusercontent.com/1037176/41396936-5efb0e22-6f67-11e8-8bf9-3d7687ab5aeb.PNG)

I had a time holding all this together to get a photo, so the issue is a little exaggerated in this photo, but it shows the amount of distance expected between the switch lever itself and the switch body's little ridge that slides on the case:

![zoom-3](https://user-images.githubusercontent.com/1037176/41396997-9ca8d9fc-6f67-11e8-809b-b8f98776a2b5.PNG)

I looked around and couldn't seem to find anyone else talking about this. I've tried this with a cheap cloned case from ebay and an original game boy case and they both have the same issue.

So, as far as I can tell, there are a few ways of addressing this. I was able to get things working by carefully cutting the switch lever down:

![zoom-4](https://user-images.githubusercontent.com/1037176/41398059-f0473150-6f6a-11e8-99aa-93be251d1fc4.PNG)

But I know the new switch was specifically changed to be longer so I'm not sure if this is the right way to go.

In any case, it would be good to have a note on this added to the wiki... once there's a "correct" way to do so!

**Comment by kiteretro** [comment]
Hi, cut the switch plastic shorter to fit properly. Resting the black plastic on some wood and using a sharp cutting knife works well!

**Comment by jamesalmeida** [comment]
Yeah I chopped the switch shorter on mine and it fits like a glove now.
