### ISSUE TITLE
[Resource/Documentation] Joycon FPC breakout board

### ISSUE THREAD

**Issue by dmradford** [kiteretro/Circuit-Sword#58]
There seems to be almost no information on what breakout board is needed for joycon joysticks, or where to get said breakout board. Is there a possibility of getting some information on this?

**Comment by kiteretro** [comment]
Hi, you need a 5P 0.5mm FPC connector with adaper board. These are hard to find, but you can use a 6P (6 pins) adapter, which are easier to find, instead.. as long as you align the connector to the side then it'll work fine. You can see the pictures on the wiki as I used a 6P adapter of my own design and making!

**Comment by kiteretro** [comment]
Added to page https://github.com/kiteretro/Circuit-Sword/wiki/Joystick-Guide
