### ISSUE TITLE
Black screen when HDMI is connected with internal screen resolution 640x480

### ISSUE THREAD

**Issue by starmagoo** [kiteretro/Circuit-Sword#59]
After the CSO is connected to an external Screen it shows a black screen if the internal screen has a resolution higher than 320x240. The resolution is recognized correctly.

After switching the internal screen in config.txt to 320x240 for testing HDMI, the internal screen isn't displaying correctly but the external screen works.

Seems to be the 640x480 LCD timing may be messing up the HDMI output.

A solution could be the one time reboot to HDMI like this ticket #28

**Comment by kiteretro** [comment]
Fixed in https://github.com/kiteretro/Circuit-Sword/releases/tag/v1.3.0

Although, if you have the 640x480 LCD the DPI CLONER doesn't work, however you can do the 'one time reboot to HDMI' from retropie menu, which WILL work :)
