### ISSUE TITLE
Grey colours are purple in LCD (gamma issues?)

### ISSUE THREAD

**Issue by piklz** [kiteretro/Circuit-Sword#66]
Happens with the 320 and 640 lcd screen

**Comment by kiteretro** [comment]
Could you post a picture on the ‘tester’ screen that shows the colour bars?

**Comment by piklz** [comment]
![20181005_080606](https://user-images.githubusercontent.com/2213075/46521162-8d78cb00-c876-11e8-9b6d-0739e1d84d6f.jpg)

**Comment by kiteretro** [comment]
Ah jeez looks like I dropped the ball on this one.. could you send me an email with your address and I’ll send a replacement ASAP! No need to send that one back. This one will not have this issue! Really sorry about that..

**Comment by piklz** [comment]
hey Kite, I replied to our conversation via kite@kitesitemshop.com with my address many thanks again for helping out so quickly.
p.s  -none the less, i've enjoyed playing the games on the gameboy even in this state and the new hud is sublime ! keep up the good work- @pixelpiklz

**Comment by kiteretro** [comment]
Fantastic :) all received and ready to be sent on Monday! That's good to hear, should just be a straight board swap when it arrives to you ;) I'll put the updated firmware on the board which actually improves the colours on 640x480 (just committed that this morning) so you should be pretty good to go!

**Comment by piklz** [comment]
new cm3 fixed this colour issues!thanks kite colours are great

**Comment by kiteretro** [comment]
Fantastic :) that's good to hear, and especially so seeing as it wasn't my board bu the CM3 itself! :tada: although that wasn't expected..
