### ISSUE TITLE
CM3 Dienst start only with micro usb 

### ISSUE THREAD

**Issue by TigerClaw33** [kiteretro/Circuit-Sword#70]
Hi,
I tried to start the sword with cm3 only with micro usb. No battery connected. But it doesn't start completely. It boot's up but before emulation station can start it shows very bright screen and boot up again. with battery it's working fine. Do you think its because it was connected to the usb port of my pc and without a battery it's not enough power to boot up ?

**Comment by kiteretro** [comment]
Yeah that is expected, the CM3 is like a Pi3, but with more stuff like the screen and audio chips etc.. so it pulls more power than your PC can provide. If you have a thick USB cable (high current) and a 5v 2.5A/3A power brick it should work fine.. with the battery connected, it acts like a buffer and can provide the extra power when needed (likely at that point in boot it starts enabling a load of stuff!)
