### ISSUE TITLE
5V for LEDs

### ISSUE THREAD

**Issue by TigerClaw33** [kiteretro/Circuit-Sword#72]
Hi, 
I have 3 LED modules rated for 5V which I use for normal Gameboy mods. First is  it possible to connect them to 5V on sword? where can I connect this to the sword exactly ?

**Comment by kiteretro** [comment]
If you look on the bottom of the board you have a number of labelled solder holes. There is 5v there :) if possible i'd recommend using 3.3v as there is another set of holes near the bottom by the audio IC (labelled 3.3v and GND)

**Comment by TigerClaw33** [comment]
The LEDs are small specific design so I will not be able to change the voltage from 5V to 3.3V ;)

**Comment by kiteretro** [comment]
Awesome :) look forward to seeing!!
