### ISSUE TITLE
[Update] Wiki being updated..

### ISSUE THREAD

**Issue by jamesalmeida** [kiteretro/Circuit-Sword#78]
Seems like a lot of the Wiki info is gone. Has it been moved? I'm hoping to update my board to most current software but don't see anything in the wiki about it anymore.

**Comment by kiteretro** [comment]
It’s in the process of being updated and that info will be in there hopefully end of tomorrow, but every day something is being added and streamlined :) it was all a bit disjointed and was only patched each time that I edited it.. doing a proper job this time round!

**Comment by JustinBenedick** [comment]
please let me know when its all back up.  A friend of mine has some concerns about his cso and we wanted to see how its put together.

**Comment by kiteretro** [comment]
The majority of text is complete (and condensed to the two main pages). Images will be going up hopefully this week

**Comment by kiteretro** [comment]
The wiki is 98% updated. There are a few images in the setup process that will be updated slightly, other than that the content is there!
