### ISSUE TITLE
battery not charging

### ISSUE THREAD

**Issue by lord-of-misrule** [kiteretro/Circuit-Sword#94]
So I finally finished my build and have been adding roms, but helder's megabat doesn't hold a charge. the red light flashes that its charging, even shows the screw tool over the battery icon, but it doesnt charge. also sometime the red charging light stays on even after unplugging it, requires a restart to turn off.

any ideas?

**Comment by kiteretro** [comment]
Hi, could you send support emails to kite@kiteretro.com. Could you please send a picture of the board powered on, with the battery connected and charger, showing the side with all the LEDs?
