### ISSUE TITLE
Circuit Sword Lite no sound

### ISSUE THREAD

**Issue by FyLapS** [kiteretro/Circuit-Sword#96]
![IMG_20191027_135205](https://user-images.githubusercontent.com/57072057/67639089-fc7df300-f8c1-11e9-83ac-604e1dc2472b.jpg)

Hello,

I'm finishing up my GBZ build and I'm having a bit of trouble with sound. I do not get any sound out of speaker or through the headphone jack.

The mute toggle is on the screen but I cannot seem to turn it off.

When I run tester mode i get a fail on the sound check. Haven't been able to figure it out since the original test I did when I got the board. I also get "failed to load mixer" messages.

I tried measuring the voltage when the speaker was unplugged and plugged in and each time which is consistently: 0.234 V from GND to S+ and 0.239 from GND to S-

I've looked through a few issues posted but cannot seem to find a solution. Any help would be greatly appreciated! 

Cheers

**Comment by kiteretro** [comment]
Audio fail means it isn’t being detected on the USB bus. I would double check the soldering of the 3pin wire to the Pi. Ideally use a multimeter to check if any of the wires are shorted together! The most common thing is a bit of solder touching the exposed metal near the test pads, so check that? Maybe take a really close up pic of that soldering?

**Comment by FyLapS** [comment]
![941C85B8-3866-45B1-9075-17C1EE6ED49A](https://user-images.githubusercontent.com/57072057/67639442-e2461400-f8c5-11e9-9cab-88659caad1b1.jpeg)


Tried with my multimeter and there is no short between any of the wires, or even the yellow wire and the hole right next to it (on the right).

There are no issues with using the USB port that I can see btw (dont know if that helps). I managed to upload games via a USB stick.

Cheers

**Comment by FyLapS** [comment]
I just noticed C20 and C21 short (the bottom connection). Should they be shorting there?

**Comment by kiteretro** [comment]
C20 and C21 are fine like that, they're meant to be connected. Oh I see the issue! You have turned the "EXT-USB-EN" switch ON, you need to turn that OFF ;)

**Comment by FyLapS** [comment]
All set thanks! Tester mode passed after i flipped the switch. Then it was a matter of turning WIFI off to get the sound to work!

Much appreciated and thanks for the support!!

**Comment by kiteretro** [comment]
No problem, anything else just email :)
